### ISSUE TITLE
GSGUIPanel::DoResize() causing exceptions

### ISSUE THREAD

**Issue by xTVaser** [xTVaser/pcsx2-rr#1]
I see that there were commits in this area to prevent exceptions from happening, but they appear to be back in the 1.5.X codebase.

I have disabled the lines for now https://github.com/xTVaser/pcsx2-rr/commit/d1a2d006613e0d481662f7740de096787b8b86d0#diff-d32bc35f2098a256f429f22a1c90d129R500  and this allows for a successful build with no exceptions and I have not seen any problems introduced with the lines disabled (but I'm unfamiliar with what this code does)

@DocSkellington

**Comment by DocSkellington** [comment]
Thank you for pointing this out. I'll take a look once I'm home (in January).

If it works with the disabled lines, let's keep it like this for the moment ;)
