### ISSUE TITLE
Minor - Default BIOS location

### ISSUE THREAD

**Issue by Wulf2k** [xTVaser/pcsx2-rr#11]
Fresh download of v1.0.1 release, go to select BIOS, default folder is as below:

C:\Users\xtvas\Documents\PCSX2\bios

Would probably be ideal to make it default to a relative path from the EXE's folder instead.

Feel free to close and ignore.

**Comment by mirh** [comment]
Pcsx2 (upstream one, at least) already works that way when it finds `portable.ini`

**Comment by xTVaser** [comment]
This is just due to how the release zip was bundled up.  Excluding the `portable.ini` from the release should solve this.
