### ISSUE TITLE
[Feature Request]: Please release a SSE4 Build for PCSX2 x64 

### ISSUE THREAD

**Issue by pantsuteam** [xTVaser/pcsx2-rr#114]
### Description

Hello, my processor is old and does not support AVX2, only AVX1 is supported. Since SSE4 is still supported at official PCSX2 build, please consider included a SSE4 version at well!

### Reason

the reason is  my cpu does not support AVX2

### Examples

Just look at official PCSX2 build

**Comment by xTVaser** [comment]
Done! https://github.com/xTVaser/pcsx2-rr/releases/tag/128mb%2Fv2.0.2
