### ISSUE TITLE
[Feature Request]: Save States Backup

### ISSUE THREAD

**Issue by sixSextant** [xTVaser/pcsx2-rr#124]
### Description

The ordinary PCSX2 comes with an option that enables users to have a save state backup to recover from in case things go south like overwriting the previous state. However, the latest stable version of this PCSX2-rr seems to drop it. 

### Reason

Users don't have backups anymore, which is bad. 

### Examples

PCSX2:
![image](https://github.com/xTVaser/pcsx2-rr/assets/50039750/061bd98e-6b80-4053-8e00-2c386368d23b)

**Comment by xTVaser** [comment]
https://github.com/xTVaser/pcsx2-rr?tab=readme-ov-file#future-of-this-repository
