### ISSUE TITLE
[Feature Request]: How to run Lua scripts?

### ISSUE THREAD

**Issue by omgitsraven** [xTVaser/pcsx2-rr#125]
### Description

Sorry if this is a silly question, but: I can't find where in the interface to run lua scripts?   I'm running the last release version (128mb/v2.0.3) and I've looked through the entire interface and I can't find anything about running lua scripts.  Was the feature removed?  Or does some setting need to be enabled to show it?

### Reason

Hoping to look around the contents of the game's RAM, and make some things found there human-readable, as well as take automated screenshots

### Examples

I've been able to do similar things in Mesen (for the NES) and Bizhawk (for the SNES)

**Comment by omgitsraven** [comment]
For anyone else running into this: don't actually use the latest release; go back to this one: https://github.com/xTVaser/pcsx2-rr/releases/tag/rr-1.0.1

leaving the issue open because I'm still not sure if I'm just doing something wrong in the latest version, but at least this works around it

**Comment by xTVaser** [comment]
The lua scripting was in the original pcsx2-rr implementation by the original author, back in 2017/2018.  It was removed when it was first added to the official pcsx2 as it wasn't suitable.

If you actually need the 128mb version then this repo's releases are useful, if you just wantthe input recording stuff, then you should be using the official pcsx2 release (input recording was added many many years ago) or potentially open a feature request there for Lua.

Looks like i accidentally commited the main repository's issue templates here but this repo is basically just my personal fork of pcsx2 and not a distinct project. https://github.com/xTVaser/pcsx2-rr#future-of-this-repository
