### ISSUE TITLE
[Feature Request]:  changelog + name of project

### ISSUE THREAD

**Issue by 7zxkv** [xTVaser/pcsx2-rr#131]
### Description

Hi,

Since RR was merged into the main project, I haven't been able to grasp what this project brings to the table. Would it be possible to provide a changelog (even a very quick one) for each release? Also, could there be an up-to-date description of what this project now offers compared to the original on the home page?  Finally, would it be possible to give this project a different name, as was the case with PCSX2-RR or PCSX2-128mb at the time the programme was run, for greater consistency? 

These are small details, but they would make things clearer for lambda users like me. Thank you for your work and for contributing to this project for so many years.

Best regards.

nb: sorry for my bad english.

### Reason

 -

### Examples

 -

**Comment by xTVaser** [comment]
The point of this repository is explained in the main readme https://github.com/xTVaser/pcsx2-rr?tab=readme-ov-file#future-of-this-repository

It has gone back to just being my personal fork of pcsx2 -- the recent releases are me testing out changes to main project's release pipeline.  So there isn't a point to the changelog.

The only significant thing that this repo provides at this point is the 128mb builds which are useful if you need to simulate a TOOL (which had 128mb of RAM).
