### ISSUE TITLE
(Feature Request) Stop internal GSdx video recording after playback of a p2m2 file is done

### ISSUE THREAD

**Issue by bositman** [xTVaser/pcsx2-rr#14]
Using the PCSX2 PR build of pcsx2-rr

Just a feature request, since I am already using the great features you guys added to record PCSX2 gameplay much faster.

My workflow is 
1) Record a keystroke session
2) Play it back and record the playthrough with GSdx video recorder

The issue here is because I'm recording at lossless quality, I get pretty low FPS so I usually just let PCSX2 run until its through, then come back and end recording. But after the p2m2 file is done it automatically pauses PCSX2, leaving the GSdx recorder running, which for me resulted in an 8 min video file but an 8 min + all time PCSX2 was paused .wav file which are out of sync. If we could have a checkbox or ini setting to end recording after the movie playback is done it would help a lot :)

I realize this is a convenience request, but I believe it should be fairly simple to add by you guys.

Thanks!

**Comment by xTVaser** [comment]
Good catch, I hadn't even considered what would happen if recording wasn't stopped while the emulator was paused.  To be honest, the fact that the video ends correctly but the audio keeps recording sounds like a bug/improvement that should be made in mainline pcsx2 (but maybe that is intended behaviour).

I like your idea of a checkbox or a setting but perhaps it might be possible to make it more intelligent and stop recording automatically if TAS playback is in progress.

Thanks, will look into it (probably after the merge into pcsx2 is finished)

**Comment by bositman** [comment]
Well I tried your 1.0.1 release from here afterwards and it *seems* it doesn't happen here. Also I had quite some crashes with the PR build, after running a game like something was stuck in memory and not cleared, making games crashing after closing and opening PCSX2 again.

It might be issues with the PR, I will retest 1.0.1 by leaving recording on after the playback has stopped for like 10 mins and see what happens.

> but perhaps it might be possible to make it more intelligent and stop recording automatically if TAS playback is in progress.
You mean stop recording automatically if TAS has also stopped? :P And maybe add some option to also start recording automatically when TAS playback starts ;)
