### ISSUE TITLE
Improve instructions for setting up dev environment

### ISSUE THREAD

**Issue by xTVaser** [xTVaser/pcsx2-rr#4]
Pretty brief at the moment, could be improved quite a bit https://github.com/xTVaser/pcsx2-rr/wiki/Building-from-Source

**Comment by Wulf2k** [comment]
I can confirm that the instructions are insufficient.

I've got the appropriate DirectX SDK installed from another project I was working on, and simply opening the SLN and hitting build didn't work, either in VS2015 or VS2017.

I haven't spent too much time on it yet but I can create an issue here with more information later on if it's something you'd like to try supporting.  I'll do my best to rule out it being a silly oversight on my part first.

**Comment by xTVaser** [comment]
Ya that would be really helpful if you could describe whatever you have to do to get things running, as it's been quite a while and its hard for me to start from a fresh environment at this point.  I'd suggest working with the solution files on master, as I've tried to clean them up a bit, maybe it was missing an option or something previously?

Someone else recently got it running, and they were successful after doing a `git clone --recursive` but I don't remember ever having to do that.

Here is all components for VS2017, having the C++ and windows SDKs definitely is required https://cdn.discordapp.com/attachments/328547679086968844/400478555336867860/unknown.png

**Comment by Wulf2k** [comment]
VS2015 on this PC

Went to https://github.com/xTVaser/pcsx2-rr

Clicked download zip

Opened pcsx2_suite.sln, Build.

First apparent error:

12>c1 : fatal error C1083: Cannot open source file: 'xz\src\liblzma\simple\x86.c': No such file or directory

This is a different PC than the first one I tried to build it on but the same error.  It's entirely possible that it's a newb-error as my programming experience is rather specialized instead of well-rounded, but I expect it would be the first thing that anybody attempting to build from scratch would run into.

I'll post back if I find the solution but I'm doing this in my spare time while working on something else today, so I'm not sure when that'll be.

**Comment by Wulf2k** [comment]
And just to confirm, I have the DX June 2010 SDK and the 2015 x86 C++ redist, on both PCs, but visually reconfirmed on this PC as well.

**Comment by xTVaser** [comment]
Hmm xz is one of the third party dependencies in the '3rdparty' folder, that's odd.  What I think I will try to do is get a fresh windows VM and go through the build process, actually documenting it along the way

**Comment by Wulf2k** [comment]
I seem to have bypassed that error by downloading from:

https://tukaani.org/xz/

and extracting the contents of xz-5.2.3.tar.gz\xz-5.2.3 to ".\3rdparty\sz\sz"

I'll just assume that downloading and compiling the first hit on google when searching for 2 arbitrary letters falls under "best practices", as the damn thing actually worked after that.  Far less of a headache than I was expecting, but this did kind of gloss over the whole SDK pre-req thing that people would run into from a completely fresh install.

**Comment by xTVaser** [comment]
Interesting, perhaps some files were lost in a merge or something, that step shouldn't be required but that is good to hear that its working now

**Comment by Wulf2k** [comment]
On my Win10/VS2017 machine, I get the following:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1189	#error:  "This version of XAudio2 is available only in Windows 8 or later. Use the XAudio2 headers and libraries from the DirectX SDK with applications that target Windows 7 and earlier versions."	Spu2-X	C:\Program Files (x86)\Windows Kits\8.1\Include\um\xaudio2.h	20	


This is with the latest DirectX and Windows 10 SDKs installed.

**Comment by xTVaser** [comment]
I suspect that you require the Windows 8.1 SDK component in Visual Studio.

I got pcsx2-rr building successfully on a completely fresh VM and recorded my steps https://github.com/xTVaser/pcsx2-rr/wiki/Building-from-Source
