### ISSUE TITLE
[BUG]: not enough cowbell

### ISSUE THREAD

**Issue by tadanokojin** [xTVaser/pcsx2-rr#92]
### Describe the Bug

application lacks cowbell

### Reproduction Steps

1. boot application
2. no cowbell

### Expected Behavior

more cowbell

### PCSX2 Revision

dev-1984

### Operating System

Windows 10 (64bit)

### CPU

ryzen 5 5600x

### GPU

gtx 1070

**Comment by xTVaser** [comment]
👎 terrible issue, banning you from the repository, never return.
